### ISSUE TITLE
Can I get SMS / Text Message for a DM on Slack?

### ISSUE THREAD

**Issue by theShiva** [nishanths/slack-texts#2]
Hi,

Is it possible to use your code, to get a SMS or Text Message on my phone, for all my DMs? I.e. if someone sends me a direct message on slack, I want to get it as a text message immediately on my phone.

**Comment by nishanths** [comment]
Currently the library filters by the `message` type, which means that only messages sent to channels are considered. https://github.com/nishanths/slack-texts/blob/master/lib/slack-texts.js#L147

Including the `message.im` type will mean that DMs are also considered. 

Note that for the `event_info` var in the code linked above, the properties for  `message.im` type events may differ from those present for  `message` type events. See the Slack docs for more info.

https://api.slack.com/events/message
https://api.slack.com/events/message.im

Hope this helps. Let me know if you have more questions. Feel free to fork or make a PR!

**Comment by theShiva** [comment]
Thanks for the instant response Nishanth!
